name: Cilium Conn Disrupt Test
description: Setup and test cilium connectivity and connection disruption status after a caller-provided risky operation, such as upgrade or IPsec key rotation.

inputs:
  job-name:
    required: true
    type: string
  operation-cmd:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup Conn Disrupt Test
      uses: cilium/little-vm-helper@0fcaa3fed17811fcd8b6f1b0dc1f24e5f4ff6b13 # v0.0.7
      with:
        provision: 'false'
        cmd: |
          cd /host/
          # Create pods which establish long lived connections. It will be used by
          # subsequent connectivity tests with --include-conn-disrupt-test to catch any
          # interruption in such flows.
          ./cilium-cli connectivity test --include-conn-disrupt-test --conn-disrupt-test-setup

    - name: Operate Cilium
      uses: cilium/little-vm-helper@0fcaa3fed17811fcd8b6f1b0dc1f24e5f4ff6b13 # v0.0.7
      with:
        provision: 'false'
        cmd: |
          ${{ inputs.operation-cmd }}

    - name: Perform Conn Disrupt Test
      uses: cilium/little-vm-helper@0fcaa3fed17811fcd8b6f1b0dc1f24e5f4ff6b13 # v0.0.7
      with:
        provision: 'false'
        cmd: |
          cd /host/
          # Disable no-missed-tail-calls due to https://github.com/cilium/cilium/issues/26739
          # Disable check-log-errors due to https://github.com/cilium/cilium-cli/issues/1858
          ./cilium-cli connectivity test --include-unsafe-tests --collect-sysdump-on-failure \
            --include-conn-disrupt-test \
            --test '!no-missed-tail-calls,!check-log-errors' \
            --flush-ct \
            --sysdump-hubble-flows-count=1000000 --sysdump-hubble-flows-timeout=5m \
            --sysdump-output-filename "cilium-sysdump-${{ inputs.job-name }}-<ts>" \
            --junit-file "cilium-junits/${{ inputs.job-name }}.xml" \
            --junit-property github_job_step="Run conn disrupt tests (${{ inputs.job-name }})"
